name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run apt update
      run: sudo apt update

    - name: Install dependencies
      run: sudo apt install -y git curl cmake pkg-config libssl-dev llvm-19-dev libclang-19-dev libpolly-19-dev libelf-dev libpcap-dev

    - name: Install Rust
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

    - name: Install nightly toolchain with rust-src
      run: |
        source $HOME/.cargo/env
        rustup toolchain install nightly --component rust-src

    - name: Install bpf-linker
      run: |
        source $HOME/.cargo/env
        cargo install bpf-linker

    - name: Build
      run: |
        source $HOME/.cargo/env
        cargo build --release